config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  get "welcome/index"
  namespace :administrate do
    resources :articles
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "welcome#index"

  # devise_for :admins do
  # get '/admins/sign_out' => 'devise/sessions#destroy'
  # end

  get "/inicio", to: "welcome#index"
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_one_attached :cover_image do |attachable|
    attachable.variant(:thumb, resize_to_limit: [100, 100])
    attachable.variant(:cover, resize_to_limit: [200, 200])
  end
end

app/controllers/administrate/articles_controller.rb
# frozen_string_literal: true

module Administrate
  class ArticlesController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    layout "administrate"

    # GET /articles or /articles.json
    def index
      @articles = Article.all
    end

    # GET /articles/1 or /articles/1.json
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles or /articles.json
    def create
      @article = Article.new(article_params)
      @article.cover_image.attach(article_params[:cover_image])

      respond_to do |format|
        if @article.save
          format.html { redirect_to(administrate_article_url(@article), notice: "Article was successfully created.") }
          format.json { render(:show, status: :created, location: @article) }
        else
          format.html { render(:new, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # PATCH/PUT /articles/1 or /articles/1.json
    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to(administrate_article_url(@article), notice: "Article was successfully updated.") }
          format.json { render(:show, status: :ok, location: @article) }
        else
          format.html { render(:edit, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # DELETE /articles/1 or /articles/1.json
    def destroy
      @article.destroy!

      respond_to do |format|
        format.html { redirect_to(administrate_article_url, status: :see_other, notice: "Article was successfully destroyed.") }
        format.json { head(:no_content) }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :cover_image)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/administrate/articles/_article.html.erb
<div id="<%= dom_id article %>">
    <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

   <p>
    <strong>Cover:</strong>
    <%= image_tag article.cover_image.variant(:thumb) if article.cover_image.attached? %>
  </p>

</div>

app/views/administrate/articles/_form.html.erb
<%= form_with(model: [:administrate, article]) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :cover_image, style: "display: block" %>
    <%= form.file_field :cover_image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/administrate/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article:  @article %>

<br>

<div>
  <%= link_to "Mostrar este artigo", [:administrate, @article] %> |
  <%= link_to "Retornar aos artigos", administrate_articles_path %>
</div>

app/views/administrate/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<p>Bem-vindo(a)! <%= current_admin.email %></p>

<%= button_to "Sair", destroy_admin_session_path, method: :delete %>


<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", [:administrate, article] %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_administrate_article_path %>

app/views/administrate/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", administrate_articles_path %>
</div>

app/views/administrate/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_administrate_article_path(@article) %> |
  <%= link_to "Back to articles", administrate_articles_path %>

  <%= button_to "Destroy this article", [:administrate, @article], method: :delete %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/layouts/administrate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyonrailsclubBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
  <h1>LAYOUT ADMINISTRATIVO</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyonrailsclubBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/_article.html.erb
<div>
  <p>
    <strong>Title:</strong>
    <%= article.title %>
    <strong>Date:</strong>
    <%= l(article.created_at, format: :only_date) %>
  </p>
</div>

app/views/welcome/index.html.erb
<h1>Articles</h1>
<p>Quantidade de Variáveis: <%= ENV.size %></p>
<p>Valor da Variável DEFAULT_PASSWORD: <%= ENV['DEFAULT_PASSWORD'] %></p>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render partial: "article", locals: { article: article } %>
  <% end %>
</div>